import { FONT_FAMILY } from "./constants";

export let textData: TextConfig[] = [
  {
    text: "canvas",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
  },
  {
    text: "fly",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
    options: {
      fillStyle: "red",
      font: `30px ${FONT_FAMILY}`,
    },
  },
  {
    text: "ABAJCIWAKSJ1",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
    options: {
      fillStyle: "red",
      font: `40px ${FONT_FAMILY}`,
    },
  },
  {
    text: "23456789",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
    options: {
      fillStyle: "red",
      font: `40px ${FONT_FAMILY}`,
    },
  },
  {
    text: "ILY",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
    options: {
      fillStyle: "red",
      font: `40px ${FONT_FAMILY}`,
    },
  },
  {
    text: "canvas",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
  },
  {
    text: "fly",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
    options: {
      fillStyle: "red",
      font: `30px ${FONT_FAMILY}`,
    },
  },
  {
    text: "CMK",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
    options: {
      fillStyle: "red",
      font: `40px ${FONT_FAMILY}`,
    },
  },
  {
    text: "酸笋,视频上传BUG修复，配置中心BUG修复",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
  },
  {
    text: "cb",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
  },
  {
    text: "a",
    left: 0,
    top: 0,
    width: 0,
    descent: 0,
    ascent: 0,
  },
];
